### ISSUE TITLE
Add UselessAssignment check

### ISSUE THREAD

**Issue by Chambeur** [BookingSync/bookingsync-stylecheck#17]
I think this check is not harmful at all and would improve readability and performance.

http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/UselessAssignment

**Comment by Mandaryn** [comment]
:+1:

**Comment by thilonel** [comment]
Is it smart enough? Can it auto correct? There shouldn't be too many of these though - hopefully not even one. I don't mind adding, but I don't mind not adding either 😄
